import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class AppLocalizations {
  final Locale locale;
  static const String _localeKey = 'app_locale';

  AppLocalizations(this.locale);

  static final ValueNotifier<Locale> localeNotifier = ValueNotifier(const Locale('en', ''));

  static Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    final langCode = prefs.getString(_localeKey) ?? 'en';
    localeNotifier.value = Locale(langCode, '');
  }

  static Future<void> setLocale(Locale locale) async {
    localeNotifier.value = locale;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_localeKey, locale.languageCode);
  }

  static void toggleLocale() {
    if (localeNotifier.value.languageCode == 'en') {
      setLocale(const Locale('ar', ''));
    } else {
      setLocale(const Locale('en', ''));
    }
  }

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'BBC Operations Platform',
      'back_to_platforms': 'Back to Platforms',
      'dashboard': 'Dashboard',
      'tasks': 'Tasks',
      'clients': 'Clients',
      'reports': 'Reports',
      'onboarding': 'Onboarding',
      'bevatel_operations': 'BEVATEL Operations Platform',
      'training_portal': 'Training Portal',
      'bbc_api_tool': 'BBC API Tool',
      'logout': 'Logout',
      'admin_console': 'Admin Console',
      'learning': 'Learning',
      'courses': 'Courses',
      'certificates': 'Certificates',
      'bevatel': 'BEVATEL',
      'operations_platform': 'Operations Platform',
      'api_collections': 'API Collections',
      'collections': 'Collections',
      'api_request': 'API Request',
      'close_request': 'Close request',
      'no_active_tasks': 'No active tasks right now.',
      'recent_clients': 'Recent Clients',
      'active_tasks': 'Active Tasks',
      'start_new_task': 'Start New Task',
      'new_task': 'New Task',
      'new_client': 'New Client',
      'language': 'Language',
      'switch_language': 'Switch Language',
      'client_overview': 'Client Overview',
      'task_overview': 'Task Overview',
      'in_progress': 'In Progress',
      'completed': 'Completed',
      'pending_activation': 'Pending Activation',
      'operational_status': 'Operational Status',
      'client_status_breakdown': 'Client Status Breakdown',
      'task_distribution': 'Task Distribution',
      'all_tasks': 'All Tasks',
      'client_tasks': 'Client Tasks',
      'internal': 'Internal',
      'tasks_today': 'Tasks Today',
      'completed_today': 'Completed Today',
      'total_completed': 'Total Completed',
      'search_clients_hint': 'Search by company name, ACC or assigned user...',
      'company_name': 'Company Name',
      'acc': 'ACC',
      'system': 'System',
      'create_client': 'Create Client',
      'cancel': 'Cancel',
      'create': 'Create',
      'activation': 'Activation',
      'verification': 'Verification',
      'chatbot': 'Chatbot',
      'group': 'Group',
      'not_started_status': 'Not Started',
      'in_progress_status': 'In Progress',
      'activated_status': 'Activated',
      'approved_status': 'Approved',
      'ready_status': 'Ready',
      'opened_status': 'Opened',
      'closed_status': 'Closed',
      'submitted_status': 'Submitted',
      'rejected_status': 'Rejected',
      'assigned': 'Assigned',
      'channels': 'Channels',
      'agent': 'Agent',
      'task_type': 'Task Type',
      'client_status': 'Client Status',
      'reset': 'Reset',
      'day': 'Day',
      'range': 'Range',
      'report_period': 'Report Period',
      'agent_occupancy': 'Agent Occupancy & Task Tracking',
      'no_agent_activity': 'No agent activity for this period.',
      'no_tasks_period': 'No tasks found for this period.',
      'task_activity': 'Task Activity',
      'task_performance': 'Task Performance',
      'no_task_data': 'No task data for this period.',
      'onboarding_stage_breakdown': 'Onboarding Stage Breakdown',
      'client_progress': 'Client Progress',
      'no_clients_match': 'No clients match the selected filters.',
      'my_clients': 'My Clients',
      'active_tasks_label': 'Active Tasks',
      'task_history': 'Task History',
      'selected_day': 'Selected Day',
      'all_history': 'All History',
      'previous_day': 'Previous day',
      'next_day': 'Next day',
      'start_task': 'Start Task',
      'tasks_description': 'Track your onboarding workload and daily occupancy.',
      'client_workspace': 'Client Workspace',
      'overview': 'Overview',
      'activity': 'Activity',
      'back_to_clients': 'Back to Clients',
      'failed_load_client': 'Failed to load client',
      'client_not_found': 'Client not found.',
      'api_operations': 'API Operations',
      'select_request_sidebar': 'Select a request from the collections sidebar to start testing APIs.',
      'sign_in_title': 'Sign in to BBC Operations Platform',
      'email': 'Email',
      'password': 'Password',
      'login': 'Login',
      'forgot_password': 'Forgot Password?',
      'email_required': 'Email is required',
      'valid_email': 'Enter a valid email',
      'password_required': 'Password is required',
      'training_dashboard': 'Training Dashboard',
      'my_learning': 'My Learning',
      'overall_progress': 'Overall Progress',
      'courses_in_progress': 'Courses in Progress',
      'completed_courses': 'Completed Courses',
      'total_learning_time': 'Total Learning Time',
      'continue_learning': 'Continue Learning',
      'no_courses_started': 'No courses started yet.',
      'recent_activity': 'Recent Activity',
      'welcome': 'Welcome',
      'manage_platforms': 'Manage your platforms and operational workspace from here.',
      'platform_overview': 'Platform Overview',
      'available': 'Available',
      'navigation': 'Navigation',
      'navigation_desc': 'Use the sidebar to switch between platforms. Each platform manages its own internal navigation.',
      'training_time': 'Training Time',
      'client_info': 'Client Information',
      'integration_details': 'Integration Details',
      'group_info': 'Group Information',
      'integrated_channels': 'Integrated Channels',
      'crm_comment': 'CRM Comment',
      'last_submitted_comment': 'Last Submitted Comment',
      'submit_comment': 'Submit Comment',
      'record_info': 'Record Information',
      'created': 'Created',
      'last_updated': 'Last Updated',
      'unnamed_client': 'Unnamed Client',
      'ownership': 'Ownership',
      'assigned_to': 'Assigned To',
      'created_by': 'Created By',
      'no_channels_yet': 'No channels added yet.',
      'edit_client_info': 'Edit Client Information',
      'save_changes': 'Save Changes',
      'submitting': 'Submitting...',
      'onboarding_dashboard_desc': 'Here is your current onboarding workload and client status.',
      'operational_status_desc': 'Current distribution across your assigned clients.',
      'active_clients': 'Active Clients',
      'opened_groups': 'Opened Groups',
      'closed_groups': 'Closed Groups',
      'recent_clients_desc': 'Latest activity on your assigned clients.',
      'no_assigned_clients': 'No assigned clients yet.',
      'active_tasks_desc': 'Tasks currently running.',
      'client_status_desc': 'Live distribution across each onboarding stage.',
      'task_distribution_desc': 'Task workload by operational type.',
      'no_task_history': 'No task history yet.',
      'phone_number_id': 'Phone Number ID',
      'phone_number': 'Phone Number',
      'status': 'Status',
      'opened': 'Opened',
      'closed': 'Closed',
      'send_crm_note': 'Send a note directly to the CRM system.',
      'write_crm_comment': 'Write a comment to send to CRM...',
      'unauthorized_edit': 'You are not authorized to edit this client.',
      'acc_number': 'ACC Number',
      'system_change_desc': 'System classification can be changed between New and Old.',
      'company_acc_required': 'Company Name and ACC Number are required.',
      'client_info_updated': 'Client information updated successfully.',
      'overall_training_progress': 'Overall Training Progress',
      'overall_progress_desc': 'Your progress across all available training courses.',
      'pick_up_where': 'Pick up where you left off.',
      'completed_tasks': 'Completed Tasks',
      'tracked_time': 'Tracked Time',
      'client_onboarding_status': 'Client Onboarding Status',
      'of_total_completed': 'of {total} completed',
      'completion_rate': '{rate}% completion rate',
      'no_tasks_day': 'No tasks for this day.',
      'start_task_desc': 'Start a task when you begin working on an onboarding activity.',
      'my_clients_label': 'My Clients',
      'in_progress_label': 'In Progress',
      'completed_label': 'Completed',
      'pending_activation_label': 'Pending Activation',
      'bevatel_label': 'BEVATEL',
      'welcome_there': 'there',
      'integration_instruction': 'Use the sidebar to switch between platforms. Each platform manages its own internal navigation.',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'jan': 'Jan', 'feb': 'Feb', 'mar': 'Mar', 'apr': 'Apr', 'may': 'May', 'jun': 'Jun',
      'jul': 'Jul', 'aug': 'Aug', 'sep': 'Sep', 'oct': 'Oct', 'nov': 'Nov', 'dec': 'Dec',
      'client_group_follow_up': 'Client Group Follow Up',
      'call': 'Call',
      'meeting': 'Meeting',
      'client_follow_up': 'Client Follow Up',
      'filter_by_date': 'Filter by Date',
      'running': 'RUNNING',
      'task_finished_success': 'Task finished successfully.',
      'failed_finish_task': 'Failed to finish task',
      'task_started_success': 'Task started successfully.',
      'failed_create_task': 'Failed to create task',
      'task': 'Task',
      'what_working_on': 'What are you working on?',
      'client': 'Client',
      'select_client': 'Select client',
      'department': 'Department',
      'elapsed': 'Elapsed',
      'finish': 'Finish',
      'send': 'Send',
      'authorization': 'Authorization',
      'bearer_token': 'Bearer Token',
      'url_variables': 'URL Variables',
      'headers': 'Headers',
      'body_placeholders': 'Body Placeholders',
      'response': 'Response',
      'continue': 'Continue',
      'analyze_onboarding': 'Analyze onboarding performance and workload.',
      'no_activity_found': 'No activity found.',
      'no_data': 'No data.',
      'no_clients': 'No clients.',
      'no_tasks': 'No tasks.',
      'access_denied': 'Access Denied',
      'super_admin_only': 'Only Super Admins can view reports.',
      'error': 'Error',
      'no_clients_found': 'No clients',
      'client_task': 'Client task',
      'business_chat': 'Business Chat',
      'account_manager': 'Account Manager',
      'sales': 'Sales',
      'voip': 'VoIP',
    },
    'ar': {
      'app_title': 'منصة عمليات BBC',
      'back_to_platforms': 'العودة إلى المنصات',
      'dashboard': 'لوحة التحكم',
      'tasks': 'المهام',
      'clients': 'العملاء',
      'reports': 'التقارير',
      'onboarding': 'التهيئة',
      'sign_in_title': 'تسجيل الدخول إلى منصة عمليات BBC',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'login': 'تسجيل الدخول',
      'forgot_password': 'نسيت كلمة المرور؟',
      'email_required': 'البريد الإلكتروني مطلوب',
      'valid_email': 'أدخل بريداً إلكترونياً صالحاً',
      'password_required': 'كلمة المرور مطلوبة',
      'bevatel_operations': 'منصة عمليات بيفاتيل',
      'training_portal': 'بوابة التدريب',
      'bbc_api_tool': 'أداة BBC API',
      'logout': 'تسجيل الخروج',
      'admin_console': 'لوحة التحكم للمسؤول',
      'learning': 'التعلم',
      'courses': 'الدورات',
      'certificates': 'الشهادات',
      'bevatel': 'بيفاتيل',
      'operations_platform': 'منصة العمليات',
      'api_collections': 'مجموعات API',
      'collections': 'المجموعات',
      'api_request': 'طلب API',
      'close_request': 'إغلاق الطلب',
      'authorization': 'التفويض',
      'bearer_token': 'توكن Bearer',
      'url_variables': 'متغيرات URL',
      'headers': 'العناوين (Headers)',
      'body_placeholders': 'عناصر نص الطلب (Body)',
      'response': 'الرد (Response)',
      'continue': 'استمرار',
      'analyze_onboarding': 'تحليل أداء التهيئة وضغط العمل.',
      'no_activity_found': 'لم يتم العثور على أي نشاط.',
      'no_data': 'لا توجد بيانات.',
      'no_clients': 'لا يوجد عملاء.',
      'no_tasks': 'لا توجد مهام.',
      'error': 'خطأ',
      'no_clients_found': 'لا يوجد عملاء',
      'select_client': 'اختر العميل',
      'client_task': 'مهمة عميل',
      'business_chat': 'دردشة الأعمال',
      'account_manager': 'مدير حسابات',
      'sales': 'المبيعات',
      'voip': 'خدمات الهاتف عبر الإنترنت',
      'access_denied': 'تم رفض الوصول',
      'super_admin_only': 'يمكن للمسؤولين فقط عرض التقارير.',
      'no_active_tasks': 'لا توجد مهام نشطة حالياً.',
      'recent_clients': 'العملاء الحاليين',
      'active_tasks': 'المهام النشطة',
      'start_new_task': 'بدء مهمة جديدة',
      'new_task': 'مهمة جديدة',
      'new_client': 'عميل جديد',
      'language': 'اللغة',
      'switch_language': 'تبديل اللغة',
      'client_overview': 'نظرة عامة على العملاء',
      'task_overview': 'نظرة عامة على المهام',
      'in_progress': 'قيد التنفيذ',
      'completed': 'مكتمل',
      'pending_activation': 'بانتظار التفعيل',
      'operational_status': 'الحالة التشغيلية',
      'client_status_breakdown': 'تحليل حالة العملاء',
      'task_distribution': 'توزيع المهام',
      'all_tasks': 'جميع المهام',
      'client_tasks': 'مهام العملاء',
      'internal': 'داخلي',
      'tasks_today': 'مهام اليوم',
      'completed_today': 'مكتمل اليوم',
      'total_completed': 'إجمالي المكتمل',
      'search_clients_hint': 'البحث باسم الشركة أو رقم الحساب أو المستخدم المكلف...',
      'company_name': 'اسم الشركة',
      'acc': 'رقم الحساب',
      'system': 'النظام',
      'create_client': 'إنشاء عميل',
      'cancel': 'إلغاء',
      'create': 'إنشاء',
      'activation': 'التفعيل',
      'verification': 'التحقق',
      'chatbot': 'روبوت الدردشة',
      'group': 'المجموعة',
      'not_started_status': 'لم يبدأ',
      'in_progress_status': 'قيد التنفيذ',
      'activated_status': 'مفعل',
      'approved_status': 'معتمد',
      'ready_status': 'جاهز',
      'opened_status': 'مفتوح',
      'closed_status': 'مغلق',
      'submitted_status': 'تم التقديم',
      'rejected_status': 'مرفوض',
      'assigned': 'مكلف لـ',
      'channels': 'القنوات',
      'agent': 'الموظف',
      'task_type': 'نوع المهمة',
      'client_status': 'حالة العميل',
      'reset': 'إعادة ضبط',
      'day': 'يوم',
      'range': 'فترة',
      'report_period': 'فترة التقرير',
      'agent_occupancy': 'إشغال الموظفين وتتبع المهام',
      'no_agent_activity': 'لا يوجد نشاط للموظفين في هذه الفترة.',
      'no_tasks_period': 'لم يتم العثور على مهام في هذه الفترة.',
      'task_activity': 'نشاط المهام',
      'task_performance': 'أداء المهام',
      'no_task_data': 'لا توجد بيانات مهام لهذه الفترة.',
      'onboarding_stage_breakdown': 'تحليل مراحل التهيئة',
      'client_progress': 'تقدم العميل',
      'no_clients_match': 'لا يوجد عملاء يطابقون الفلاتر المختارة.',
      'my_clients': 'عملائي',
      'active_tasks_label': 'المهام النشطة',
      'task_history': 'سجل المهام',
      'selected_day': 'اليوم المحدد',
      'all_history': 'السجل الكامل',
      'previous_day': 'اليوم السابق',
      'next_day': 'اليوم التالي',
      'start_task': 'بدء المهمة',
      'tasks_description': 'تتبع ضغط عملك في التهيئة والإشغال اليومي.',
      'client_workspace': 'مساحة عمل العميل',
      'overview': 'نظرة عامة',
      'activity': 'النشاط',
      'back_to_clients': 'العودة إلى العملاء',
      'failed_load_client': 'فشل تحميل بيانات العميل',
      'client_not_found': 'العميل غير موجود.',
      'training_dashboard': 'لوحة تحكم التدريب',
      'my_learning': 'تعليمي',
      'overall_progress': 'التقدم الإجمالي',
      'courses_in_progress': 'دورات قيد التنفيذ',
      'completed_courses': 'دورات مكتملة',
      'total_learning_time': 'إجمالي وقت التعلم',
      'continue_learning': 'مواصلة التعلم',
      'no_courses_started': 'لم تبدأ أي دورات بعد.',
      'recent_activity': 'النشاط الأخير',
      'welcome': 'مرحباً بك',
      'manage_platforms': 'قم بإدارة منصاتك ومساحة العمل التشغيلية من هنا.',
      'platform_overview': 'نظرة عامة على المنصة',
      'available': 'متاح',
      'navigation': 'التنقل',
      'navigation_desc': 'استخدم الشريط الجانبي للتنقل بين المنصات. كل منصة تدير تنقلها الداخلي.',
      'training_time': 'وقت التدريب',
      'client_info': 'بيانات العميل',
      'integration_details': 'بيانات الربط',
      'group_info': 'بيانات المجموعة',
      'integrated_channels': 'القنوات المربوطة',
      'crm_comment': 'ملاحظة CRM',
      'last_submitted_comment': 'آخر ملاحظة تم تقديمها',
      'submit_comment': 'تقديم الملاحظة',
      'record_info': 'بيانات السجل',
      'created': 'تم الإنشاء',
      'last_updated': 'آخر تحديث',
      'unnamed_client': 'عميل بدون اسم',
      'ownership': 'الملكية',
      'assigned_to': 'مكلف لـ',
      'created_by': 'أنشئ بواسطة',
      'no_channels_yet': 'لم يتم إضافة قنوات بعد.',
      'edit_client_info': 'تعديل بيانات العميل',
      'save_changes': 'حفظ التغييرات',
      'submitting': 'جاري التقديم...',
      'onboarding_dashboard_desc': 'إليك ضغط عملك الحالي في التهيئة وحالة العملاء.',
      'operational_status_desc': 'التوزيع الحالي عبر العملاء المكلفين إليك.',
      'active_clients': 'العملاء النشطون',
      'opened_groups': 'المجموعات المفتوحة',
      'closed_groups': 'المجموعات المغلقة',
      'recent_clients_desc': 'آخر نشاط على العملاء المكلفين إليك.',
      'no_assigned_clients': 'لا يوجد عملاء مكلفون بعد.',
      'active_tasks_desc': 'المهام التي قيد التنفيذ حالياً.',
      'client_status_desc': 'التوزيع المباشر عبر كل مرحلة تهيئة.',
      'task_distribution_desc': 'توزيع ضغط العمل حسب النوع التشغيلي.',
      'no_task_history': 'لا يوجد سجل مهام بعد.',
      'phone_number_id': 'رقم تعريف الهاتف',
      'phone_number': 'رقم الهاتف',
      'status': 'الحالة',
      'opened': 'مفتوح',
      'closed': 'مغلق',
      'send_crm_note': 'إرسال ملاحظة مباشرة إلى نظام CRM.',
      'write_crm_comment': 'اكتب ملاحظة لإرسالها إلى CRM...',
      'unauthorized_edit': 'ليس لديك صلاحية لتعديل هذا العميل.',
      'acc_number': 'رقم الحساب',
      'system_change_desc': 'يمكن تغيير تصنيف النظام بين قديم وجديد.',
      'company_acc_required': 'اسم الشركة ورقم الحساب مطلوبان.',
      'client_info_updated': 'تم تحديث بيانات العميل بنجاح.',
      'overall_training_progress': 'التقدم الإجمالي للتدريب',
      'overall_progress_desc': 'تقدمك في جميع الدورات التدريبية المتاحة.',
      'pick_up_where': 'تابع من حيث توقفت.',
      'completed_tasks': 'المهام المكتملة',
      'tracked_time': 'الوقت المسجل',
      'client_onboarding_status': 'حالة تهيئة العملاء',
      'of_total_completed': 'من {total} مكتمل',
      'completion_rate': '{rate}% معدل الإكمال',
      'no_tasks_day': 'لا توجد مهام لهذا اليوم.',
      'start_task_desc': 'ابدأ مهمة عند البدء في أي من أنشطة التهيئة.',
      'my_clients_label': 'عملائي',
      'in_progress_label': 'قيد التنفيذ',
      'completed_label': 'مكتمل',
      'pending_activation_label': 'بانتظار التفعيل',
      'today': 'اليوم',
      'yesterday': 'أمس',
      'jan': 'يناير', 'feb': 'فبراير', 'mar': 'مارس', 'apr': 'أبريل', 'may': 'مايو', 'jun': 'يونيو',
      'jul': 'يوليو', 'aug': 'أغسطس', 'sep': 'سبتمبر', 'oct': 'أكتوبر', 'nov': 'نوفمبر', 'dec': 'ديسمبر',
      'client_group_follow_up': 'متابعة مجموعة العملاء',
      'call': 'مكالمة',
      'meeting': 'اجتماع',
      'client_follow_up': 'متابعة العميل',
      'filter_by_date': 'البحث بالتاريخ',
      'running': 'قيد التنفيذ',
      'task_finished_success': 'تم إنهاء المهمة بنجاح.',
      'failed_finish_task': 'فشل إنهاء المهمة',
      'task_started_success': 'تم بدء المهمة بنجاح.',
      'failed_create_task': 'فشل إنشاء المهمة',
      'task': 'المهمة',
      'what_working_on': 'ماذا تنجز الآن؟',
      'client': 'العميل',
      'department': 'القسم',
      'elapsed': 'الوقت المنقضي',
      'finish': 'إنهاء',
    },
  };

  String translate(String key, {Map<String, String>? params}) {
    String value = _localizedValues[locale.languageCode]?[key] ?? key;
    if (params != null) {
      params.forEach((k, v) {
        value = value.replaceAll('{$k}', v);
      });
    }
    return value;
  }

  String translateStatus(String status) {
    final normalized = status.trim().toLowerCase();
    if (normalized.isEmpty || normalized == 'not started') {
      return translate('not_started_status');
    }
    
    // Check for direct matches first
    final key = '${normalized.replaceAll(' ', '_')}_status';
    final translated = translate(key);
    
    if (translated != key) {
      return translated;
    }
    
    // Fallback if no specific translation exists
    return status;
  }

  bool get isRtl => locale.languageCode == 'ar';
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
