// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrknr-61yICu60A_uRhbO0a0FBMLOsBvA',
    appId: '1:259169067995:web:c46914fa0822888a98fdfe',
    messagingSenderId: '259169067995',
    projectId: 'bbc-api-tool',
    authDomain: 'bbc-api-tool.firebaseapp.com',
    storageBucket: 'bbc-api-tool.firebasestorage.app',
    measurementId: 'G-51Z1MV96CY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVccklkXr1ZEuQkDZt4ANedf41Uk3iQMA',
    appId: '1:259169067995:android:9df42272f819de9e98fdfe',
    messagingSenderId: '259169067995',
    projectId: 'bbc-api-tool',
    storageBucket: 'bbc-api-tool.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMrMTtVV5erlMQPbO21xBl8mJh7SLd2bs',
    appId: '1:259169067995:ios:21039dda2d978e8e98fdfe',
    messagingSenderId: '259169067995',
    projectId: 'bbc-api-tool',
    storageBucket: 'bbc-api-tool.firebasestorage.app',
    iosBundleId: 'com.example.bbcApiTool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMrMTtVV5erlMQPbO21xBl8mJh7SLd2bs',
    appId: '1:259169067995:ios:21039dda2d978e8e98fdfe',
    messagingSenderId: '259169067995',
    projectId: 'bbc-api-tool',
    storageBucket: 'bbc-api-tool.firebasestorage.app',
    iosBundleId: 'com.example.bbcApiTool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrknr-61yICu60A_uRhbO0a0FBMLOsBvA',
    appId: '1:259169067995:web:49b36decedc7584e98fdfe',
    messagingSenderId: '259169067995',
    projectId: 'bbc-api-tool',
    authDomain: 'bbc-api-tool.firebaseapp.com',
    storageBucket: 'bbc-api-tool.firebasestorage.app',
    measurementId: 'G-JLVDB5Q97S',
  );
}
